import { t } from 'i18next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import { useEffect, useState } from 'react';

import CardFour from '@/components/core/cards/CardFour';
import CardOne from '@/components/core/cards/CardOne';
import CardThree from '@/components/core/cards/CardThree';
import CardTwo from '@/components/core/cards/CardTwo';
import BarChart from '@/components/core/charts/BarChart';
import LineChart from '@/components/core/charts/LineChart';
import { Dataset } from '@/util/models/Dataset';

import Cocoa from '../../public/assets/cocoa.png';
import Farmer from '../../public/assets/farmer.png';
import Kilogram from '../../public/assets/kilogram.png';
import Aurora from '../../public/assets/logos/aurora.png';
import Man from '../../public/assets/man.png';
import Woman from '../../public/assets/woman.png';

export default function Home() {
  const [datasets, setDatasets] = useState<Dataset[]>([]);

  useEffect(() => {
    setDatasets([
      new Dataset(
        'CocoaAralambis',
        [1221, 1321, 543, 443, 543, 45, 0, 0, 10, 30],
        '#d43564'
      ),
      new Dataset(
        'Comboa',
        [221, 2321, 673, 223, 243, 75, 20, 0, 0, 0],
        '#a03564'
      ),
    ]);
  }, []);
  return (
    <>
      <Head>
        <title>Aurora - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="dashboard__container">
        <div>
          <Image
            width={200}
            height={234}
            className="dashboard__logo"
            src={Aurora.src}
            alt="Aurora"
          />
          <div className="dashboard__cards dashboard__cards--main">
            <Link href={'/availables'}>
              <CardTwo
                backgroundColor="#f1842d"
                number={200}
                text={t('dry_cocoa_available')}
                icon={Kilogram.src}
                alt={''}
              />
            </Link>
            <Link href="/sold">
              <CardTwo
                backgroundColor="#f39a1a"
                number={200}
                text={t('sold_international_market')}
                icon={Kilogram.src}
                alt={''}
              />
            </Link>
          </div>
        </div>
        <div className="dashboard__container-info">
          <div className="dashboard__cards">
            <CardOne
              backgroundColor="#d0741a"
              number={200}
              text={t('number_producers')}
              icon={Farmer.src}
              alt={'Producers'}
            />
            <CardTwo
              backgroundColor="#f1842d"
              number={200}
              text={t('number_men_under_30')}
              icon={Man.src}
              alt={'Men'}
            />
            <CardThree
              backgroundColor="#964514"
              number={200}
              text={t('number_women')}
              icon={Woman.src}
              alt={'Women'}
              maxIconWidth="145px"
            />
            <CardFour
              backgroundColor="#f39a1a"
              number={200}
              text={t('ha_forest_conservation')}
              icon={Cocoa.src}
              alt={'Forest'}
            />
          </div>
          <div className="dashboard__charts">
            <div className="dashboard__charts-production">
              <BarChart
                title={t('production_by_association')}
                datasets={datasets}
                backgroundColor="#f39a1a98"
              />
              <BarChart
                title={t('production_by_region')}
                datasets={datasets}
                backgroundColor="#96451495"
              />
            </div>
            <div className="dashboard__charts-sales">
              <LineChart
                title={t('usd_price_organic_cocoa')}
                datasets={datasets}
                backgroundColor="#c9732190"
              />
              <LineChart
                title={t('total_sales_usd')}
                datasets={datasets}
                backgroundColor="#c9732190"
              />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
